name: 'TruffleHog OSS'
description: 'Scan Github Actions with TruffleHog'
author: Truffle Security Co. <support@trufflesec.com>

inputs:
  cli_cmd:
    default: 'git file://./'
    description: 'cli command to be passed to the trufflehog cli'
    required: false
branding:
  icon: "shield"
  color: "green"
runs:
  using: "docker"
  image: "docker://ghcr.io/trufflesecurity/trufflehog:latest"
  args:
    - ${{ inputs.cli_cmd }}
